#include "gb.h"

EXT_INST(0x0, "RLC B", { undefined(); })
EXT_INST(0x1, "RLC C", { undefined(); })
EXT_INST(0x2, "RLC D", { undefined(); })
EXT_INST(0x3, "RLC E", { undefined(); })
EXT_INST(0x4, "RLC H", { undefined(); })
EXT_INST(0x5, "RLC L", { undefined(); })
EXT_INST(0x6, "RLC (HL)", { undefined(); })
EXT_INST(0x7, "RLC A", { undefined(); })
EXT_INST(0x8, "RRC B", { undefined(); })
EXT_INST(0x9, "RRC C", { undefined(); })
EXT_INST(0xA, "RRC D", { undefined(); })
EXT_INST(0xB, "RRC E", { undefined(); })
EXT_INST(0xC, "RRC H", { undefined(); })
EXT_INST(0xD, "RRC L", { undefined(); })
EXT_INST(0xE, "RRC (HL)", { undefined(); })
EXT_INST(0xF, "RRC A", { undefined(); })
EXT_INST(0x10, "RL B", { undefined(); })
EXT_INST(0x11, "RL C", { undefined(); })
EXT_INST(0x12, "RL D", { undefined(); })
EXT_INST(0x13, "RL E", { undefined(); })
EXT_INST(0x14, "RL H", { undefined(); })
EXT_INST(0x15, "RL L", { undefined(); })
EXT_INST(0x16, "RL (HL)", { undefined(); })
EXT_INST(0x17, "RL A", { undefined(); })
EXT_INST(0x18, "RR B", { undefined(); })
EXT_INST(0x19, "RR C", { undefined(); })
EXT_INST(0x1A, "RR D", { undefined(); })
EXT_INST(0x1B, "RR E", { undefined(); })
EXT_INST(0x1C, "RR H", { undefined(); })
EXT_INST(0x1D, "RR L", { undefined(); })
EXT_INST(0x1E, "RR (HL)", { undefined(); })
EXT_INST(0x1F, "RR A", { undefined(); })
EXT_INST(0x20, "SLA B", { sla8(gb.b); })
EXT_INST(0x21, "SLA C", { sla8(gb.c); })
EXT_INST(0x22, "SLA D", { sla8(gb.d); })
EXT_INST(0x23, "SLA E", { sla8(gb.e); })
EXT_INST(0x24, "SLA H", { sla8(gb.h); })
EXT_INST(0x25, "SLA L", { sla8(gb.l); })
EXT_INST(0x26, "SLA (HL)", { undefined(); })
EXT_INST(0x27, "SLA A", { sla8(gb.a); })
EXT_INST(0x28, "SRA B", { undefined(); })
EXT_INST(0x29, "SRA C", { undefined(); })
EXT_INST(0x2A, "SRA D", { undefined(); })
EXT_INST(0x2B, "SRA E", { undefined(); })
EXT_INST(0x2C, "SRA H", { undefined(); })
EXT_INST(0x2D, "SRA L", { undefined(); })
EXT_INST(0x2E, "SRA (HL)", { undefined(); })
EXT_INST(0x2F, "SRA A", { undefined(); })
EXT_INST(0x30, "SWAP B", { undefined(); })
EXT_INST(0x31, "SWAP C", { undefined(); })
EXT_INST(0x32, "SWAP D", { undefined(); })
EXT_INST(0x33, "SWAP E", { undefined(); })
EXT_INST(0x34, "SWAP H", { undefined(); })
EXT_INST(0x35, "SWAP L", { undefined(); })
EXT_INST(0x36, "SWAP (HL)", { undefined(); })
EXT_INST(0x37, "SWAP A", { swap8(gb.a); })
EXT_INST(0x38, "SRL B", { undefined(); })
EXT_INST(0x39, "SRL C", { undefined(); })
EXT_INST(0x3A, "SRL D", { undefined(); })
EXT_INST(0x3B, "SRL E", { undefined(); })
EXT_INST(0x3C, "SRL H", { undefined(); })
EXT_INST(0x3D, "SRL L", { undefined(); })
EXT_INST(0x3E, "SRL (HL)", { undefined(); })
EXT_INST(0x3F, "SRL A", { undefined(); })
EXT_INST(0x40, "BIT 0,B", { bit8(0, gb.b); })
EXT_INST(0x41, "BIT 0,C", { bit8(0, gb.c); })
EXT_INST(0x42, "BIT 0,D", { bit8(0, gb.d); })
EXT_INST(0x43, "BIT 0,E", { bit8(0, gb.e); })
EXT_INST(0x44, "BIT 0,H", { bit8(0, gb.h); })
EXT_INST(0x45, "BIT 0,L", { bit8(0, gb.l); })
EXT_INST(0x46, "BIT 0,(HL)", { bit8(0, readMemory(gb.hl)); })
EXT_INST(0x47, "BIT 0,A", { bit8(0, gb.a); })
EXT_INST(0x48, "BIT 1,B", { bit8(1, gb.b); })
EXT_INST(0x49, "BIT 1,C", { bit8(1, gb.c); })
EXT_INST(0x4A, "BIT 1,D", { bit8(1, gb.d); })
EXT_INST(0x4B, "BIT 1,E", { bit8(1, gb.e); })
EXT_INST(0x4C, "BIT 1,H", { bit8(1, gb.h); })
EXT_INST(0x4D, "BIT 1,L", { bit8(1, gb.l); })
EXT_INST(0x4E, "BIT 1,(HL)", { bit8(1, readMemory(gb.hl)); })
EXT_INST(0x4F, "BIT 1,A", { bit8(1, gb.a); })
EXT_INST(0x50, "BIT 2,B", { bit8(2, gb.b); })
EXT_INST(0x51, "BIT 2,C", { bit8(2, gb.c); })
EXT_INST(0x52, "BIT 2,D", { bit8(2, gb.d); })
EXT_INST(0x53, "BIT 2,E", { bit8(2, gb.e); })
EXT_INST(0x54, "BIT 2,H", { bit8(2, gb.h); })
EXT_INST(0x55, "BIT 2,L", { bit8(2, gb.l); })
EXT_INST(0x56, "BIT 2,(HL)", { bit8(2, readMemory(gb.hl)); })
EXT_INST(0x57, "BIT 2,A", { bit8(2, gb.a); })
EXT_INST(0x58, "BIT 3,B", { bit8(3, gb.b); })
EXT_INST(0x59, "BIT 3,C", { bit8(3, gb.c); })
EXT_INST(0x5A, "BIT 3,D", { bit8(3, gb.d); })
EXT_INST(0x5B, "BIT 3,E", { bit8(3, gb.e); })
EXT_INST(0x5C, "BIT 3,H", { bit8(3, gb.h); })
EXT_INST(0x5D, "BIT 3,L", { bit8(3, gb.l); })
EXT_INST(0x5E, "BIT 3,(HL)", { bit8(3, readMemory(gb.hl)); })
EXT_INST(0x5F, "BIT 3,A", { bit8(3, gb.a); })
EXT_INST(0x60, "BIT 4,B", { bit8(4, gb.b); })
EXT_INST(0x61, "BIT 4,C", { bit8(4, gb.c); })
EXT_INST(0x62, "BIT 4,D", { bit8(4, gb.d); })
EXT_INST(0x63, "BIT 4,E", { bit8(4, gb.e); })
EXT_INST(0x64, "BIT 4,H", { bit8(4, gb.h); })
EXT_INST(0x65, "BIT 4,L", { bit8(4, gb.l); })
EXT_INST(0x66, "BIT 4,(HL)", { bit8(4, readMemory(gb.hl)); })
EXT_INST(0x67, "BIT 4,A", { bit8(4, gb.a); })
EXT_INST(0x68, "BIT 5,B", { bit8(5, gb.b); })
EXT_INST(0x69, "BIT 5,C", { bit8(5, gb.c); })
EXT_INST(0x6A, "BIT 5,D", { bit8(5, gb.d); })
EXT_INST(0x6B, "BIT 5,E", { bit8(5, gb.e); })
EXT_INST(0x6C, "BIT 5,H", { bit8(5, gb.h); })
EXT_INST(0x6D, "BIT 5,L", { bit8(5, gb.l); })
EXT_INST(0x6E, "BIT 5,(HL)", { bit8(5, readMemory(gb.hl)); })
EXT_INST(0x6F, "BIT 5,A", { bit8(5, gb.a); })
EXT_INST(0x70, "BIT 6,B", { bit8(6, gb.b); })
EXT_INST(0x71, "BIT 6,C", { bit8(6, gb.c); })
EXT_INST(0x72, "BIT 6,D", { bit8(6, gb.d); })
EXT_INST(0x73, "BIT 6,E", { bit8(6, gb.e); })
EXT_INST(0x74, "BIT 6,H", { bit8(6, gb.h); })
EXT_INST(0x75, "BIT 6,L", { bit8(6, gb.l); })
EXT_INST(0x76, "BIT 6,(HL)", { bit8(6, readMemory(gb.hl)); })
EXT_INST(0x77, "BIT 6,A", { bit8(6, gb.a); })
EXT_INST(0x78, "BIT 7,B", { bit8(7, gb.b); })
EXT_INST(0x79, "BIT 7,C", { bit8(7, gb.c); })
EXT_INST(0x7A, "BIT 7,D", { bit8(7, gb.d); })
EXT_INST(0x7B, "BIT 7,E", { bit8(7, gb.e); })
EXT_INST(0x7C, "BIT 7,H", { bit8(7, gb.h); })
EXT_INST(0x7D, "BIT 7,L", { bit8(7, gb.l); })
EXT_INST(0x7E, "BIT 7,(HL)", { bit8(7, readMemory(gb.hl)); })
EXT_INST(0x7F, "BIT 7,A", { bit8(7, gb.a); })
EXT_INST(0x80, "RES 0,B", { undefined(); })
EXT_INST(0x81, "RES 0,C", { undefined(); })
EXT_INST(0x82, "RES 0,D", { undefined(); })
EXT_INST(0x83, "RES 0,E", { undefined(); })
EXT_INST(0x84, "RES 0,H", { undefined(); })
EXT_INST(0x85, "RES 0,L", { undefined(); })
EXT_INST(0x86, "RES 0,(HL)", { undefined(); })
EXT_INST(0x87, "RES 0,A", { res8(0, gb.a); })
EXT_INST(0x88, "RES 1,B", { undefined(); })
EXT_INST(0x89, "RES 1,C", { undefined(); })
EXT_INST(0x8A, "RES 1,D", { undefined(); })
EXT_INST(0x8B, "RES 1,E", { undefined(); })
EXT_INST(0x8C, "RES 1,H", { undefined(); })
EXT_INST(0x8D, "RES 1,L", { undefined(); })
EXT_INST(0x8E, "RES 1,(HL)", { undefined(); })
EXT_INST(0x8F, "RES 1,A", { undefined(); })
EXT_INST(0x90, "RES 2,B", { undefined(); })
EXT_INST(0x91, "RES 2,C", { undefined(); })
EXT_INST(0x92, "RES 2,D", { undefined(); })
EXT_INST(0x93, "RES 2,E", { undefined(); })
EXT_INST(0x94, "RES 2,H", { undefined(); })
EXT_INST(0x95, "RES 2,L", { undefined(); })
EXT_INST(0x96, "RES 2,(HL)", { undefined(); })
EXT_INST(0x97, "RES 2,A", { undefined(); })
EXT_INST(0x98, "RES 3,B", { undefined(); })
EXT_INST(0x99, "RES 3,C", { undefined(); })
EXT_INST(0x9A, "RES 3,D", { undefined(); })
EXT_INST(0x9B, "RES 3,E", { undefined(); })
EXT_INST(0x9C, "RES 3,H", { undefined(); })
EXT_INST(0x9D, "RES 3,L", { undefined(); })
EXT_INST(0x9E, "RES 3,(HL)", { undefined(); })
EXT_INST(0x9F, "RES 3,A", { undefined(); })
EXT_INST(0xA0, "RES 4,B", { undefined(); })
EXT_INST(0xA1, "RES 4,C", { undefined(); })
EXT_INST(0xA2, "RES 4,D", { undefined(); })
EXT_INST(0xA3, "RES 4,E", { undefined(); })
EXT_INST(0xA4, "RES 4,H", { undefined(); })
EXT_INST(0xA5, "RES 4,L", { undefined(); })
EXT_INST(0xA6, "RES 4,(HL)", { undefined(); })
EXT_INST(0xA7, "RES 4,A", { undefined(); })
EXT_INST(0xA8, "RES 5,B", { undefined(); })
EXT_INST(0xA9, "RES 5,C", { undefined(); })
EXT_INST(0xAA, "RES 5,D", { undefined(); })
EXT_INST(0xAB, "RES 5,E", { undefined(); })
EXT_INST(0xAC, "RES 5,H", { undefined(); })
EXT_INST(0xAD, "RES 5,L", { undefined(); })
EXT_INST(0xAE, "RES 5,(HL)", { undefined(); })
EXT_INST(0xAF, "RES 5,A", { undefined(); })
EXT_INST(0xB0, "RES 6,B", { undefined(); })
EXT_INST(0xB1, "RES 6,C", { undefined(); })
EXT_INST(0xB2, "RES 6,D", { undefined(); })
EXT_INST(0xB3, "RES 6,E", { undefined(); })
EXT_INST(0xB4, "RES 6,H", { undefined(); })
EXT_INST(0xB5, "RES 6,L", { undefined(); })
EXT_INST(0xB6, "RES 6,(HL)", { undefined(); })
EXT_INST(0xB7, "RES 6,A", { undefined(); })
EXT_INST(0xB8, "RES 7,B", { undefined(); })
EXT_INST(0xB9, "RES 7,C", { undefined(); })
EXT_INST(0xBA, "RES 7,D", { undefined(); })
EXT_INST(0xBB, "RES 7,E", { undefined(); })
EXT_INST(0xBC, "RES 7,H", { undefined(); })
EXT_INST(0xBD, "RES 7,L", { undefined(); })
EXT_INST(0xBE, "RES 7,(HL)", { undefined(); })
EXT_INST(0xBF, "RES 7,A", { undefined(); })
EXT_INST(0xC0, "SET 0,B", { undefined(); })
EXT_INST(0xC1, "SET 0,C", { undefined(); })
EXT_INST(0xC2, "SET 0,D", { undefined(); })
EXT_INST(0xC3, "SET 0,E", { undefined(); })
EXT_INST(0xC4, "SET 0,H", { undefined(); })
EXT_INST(0xC5, "SET 0,L", { undefined(); })
EXT_INST(0xC6, "SET 0,(HL)", { undefined(); })
EXT_INST(0xC7, "SET 0,A", { undefined(); })
EXT_INST(0xC8, "SET 1,B", { undefined(); })
EXT_INST(0xC9, "SET 1,C", { undefined(); })
EXT_INST(0xCA, "SET 1,D", { undefined(); })
EXT_INST(0xCB, "SET 1,E", { undefined(); })
EXT_INST(0xCC, "SET 1,H", { undefined(); })
EXT_INST(0xCD, "SET 1,L", { undefined(); })
EXT_INST(0xCE, "SET 1,(HL)", { undefined(); })
EXT_INST(0xCF, "SET 1,A", { undefined(); })
EXT_INST(0xD0, "SET 2,B", { undefined(); })
EXT_INST(0xD1, "SET 2,C", { undefined(); })
EXT_INST(0xD2, "SET 2,D", { undefined(); })
EXT_INST(0xD3, "SET 2,E", { undefined(); })
EXT_INST(0xD4, "SET 2,H", { undefined(); })
EXT_INST(0xD5, "SET 2,L", { undefined(); })
EXT_INST(0xD6, "SET 2,(HL)", { undefined(); })
EXT_INST(0xD7, "SET 2,A", { undefined(); })
EXT_INST(0xD8, "SET 3,B", { undefined(); })
EXT_INST(0xD9, "SET 3,C", { undefined(); })
EXT_INST(0xDA, "SET 3,D", { undefined(); })
EXT_INST(0xDB, "SET 3,E", { undefined(); })
EXT_INST(0xDC, "SET 3,H", { undefined(); })
EXT_INST(0xDD, "SET 3,L", { undefined(); })
EXT_INST(0xDE, "SET 3,(HL)", { undefined(); })
EXT_INST(0xDF, "SET 3,A", { undefined(); })
EXT_INST(0xE0, "SET 4,B", { undefined(); })
EXT_INST(0xE1, "SET 4,C", { undefined(); })
EXT_INST(0xE2, "SET 4,D", { undefined(); })
EXT_INST(0xE3, "SET 4,E", { undefined(); })
EXT_INST(0xE4, "SET 4,H", { undefined(); })
EXT_INST(0xE5, "SET 4,L", { undefined(); })
EXT_INST(0xE6, "SET 4,(HL)", { undefined(); })
EXT_INST(0xE7, "SET 4,A", { undefined(); })
EXT_INST(0xE8, "SET 5,B", { undefined(); })
EXT_INST(0xE9, "SET 5,C", { undefined(); })
EXT_INST(0xEA, "SET 5,D", { undefined(); })
EXT_INST(0xEB, "SET 5,E", { undefined(); })
EXT_INST(0xEC, "SET 5,H", { undefined(); })
EXT_INST(0xED, "SET 5,L", { undefined(); })
EXT_INST(0xEE, "SET 5,(HL)", { undefined(); })
EXT_INST(0xEF, "SET 5,A", { undefined(); })
EXT_INST(0xF0, "SET 6,B", { undefined(); })
EXT_INST(0xF1, "SET 6,C", { undefined(); })
EXT_INST(0xF2, "SET 6,D", { undefined(); })
EXT_INST(0xF3, "SET 6,E", { undefined(); })
EXT_INST(0xF4, "SET 6,H", { undefined(); })
EXT_INST(0xF5, "SET 6,L", { undefined(); })
EXT_INST(0xF6, "SET 6,(HL)", { undefined(); })
EXT_INST(0xF7, "SET 6,A", { undefined(); })
EXT_INST(0xF8, "SET 7,B", { undefined(); })
EXT_INST(0xF9, "SET 7,C", { undefined(); })
EXT_INST(0xFA, "SET 7,D", { undefined(); })
EXT_INST(0xFB, "SET 7,E", { undefined(); })
EXT_INST(0xFC, "SET 7,H", { undefined(); })
EXT_INST(0xFD, "SET 7,L", { undefined(); })
EXT_INST(0xFE, "SET 7,(HL)", { undefined(); })
EXT_INST(0xFF, "SET 7,A", { undefined(); })
